server:
  port:
    9004
eureka:
  client:
    serviceUrl:
      defaultZone:
        http://localhost:9102/eureka/
spring:
  cloud:
    gateway:
      routes:
        - id: microservice-produits
          uri: lb://MICROSERVICE-PRODUITS
          predicates:
            - Path=/api/produits/**
          filters:
            - StripPrefix=1
