server:
  port:
    9004
eureka:
  client:
    serviceUrl:
      defaultZone:
        http://app-eureka:9102/eureka/
spring:
  cloud:
    gateway:
      corsConfigurations:
        "[/**]":
          allowedOrigins: "*"
          allowedHeaders:
            - content-type
            - Authorization
            - Access-Control-Request-Method
            - Access-Control-Request-Headers
          allowedMethods:
            - GET
            - POST
            - DELETE
            - PUT
      routes:
        - id: microservice-produits
          uri: lb://MICROSERVICE-PRODUITS
          predicates:
            - Path=/api/produits/**
          filters:
            - StripPrefix=1
