server:
  port:
    9004
eureka:
  client:
    serviceUrl:
      defaultZone:
        http://localhost:9102/eureka/
spring:
  cloud:
    gateway:
      routes:
        - id: microservice-produit
          uri: lb://microservice-produit
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
