server:
  port:
    9004
eureka:
  client:
    serviceUrl:
      defaultZone:
        # http://app-eureka:9102/eureka/
        http://localhost:9102/eureka/

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem


spring:
  main:
    allow-bean-definition-overriding: true

 # jpa:
 #   generate-ddl: true
 #   show-sql: true
 #   hibernate:
 #     ddl-auto: create-drop
 # datasource:
 #   url: jdbc:mysql://localhost:3306/test_gateway?createDatabaseIfNotExist=true
 #   username: root
 #   password: admin1
  r2dbc:
    url: r2dbc:mysql://localhost:3306/test_gateway?createDatabaseIfNotExist=true
    username: root
    password: admin1
    pool:
      initial-size: 5
      max-size: 10
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  cloud:
    gateway:
      corsConfigurations:
        "[/**]":
          allowedOrigins: "*"
          allowedHeaders:
            - content-type
            - Authorization
            - Access-Control-Request-Method
            - Access-Control-Request-Headers
          allowedMethods:
            - GET
            - POST
            - DELETE
            - PUT
      routes:
        - id: microservice-produits
          uri: lb://MICROSERVICE-PRODUITS
          predicates:
            - Path=/api/produits/**
          filters:
            - StripPrefix=1
